CREATE TABLE program_locks (
	id INT NOT NULL AUTO_INCREMENT,
	program INT NOT NULL,
	name INT NOT NULL,
	start TIMESTAMP NOT NULL,
	end TIMESTAMP NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(program) REFERENCES programs(id),
	FOREIGN KEY(name) REFERENCES names(id)
);