// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/CommandBuff.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto/CommandBuff.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* CommandBuff_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommandBuff_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_proto_2fCommandBuff_2eproto() {
  protobuf_AddDesc_proto_2fCommandBuff_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "proto/CommandBuff.proto");
  GOOGLE_CHECK(file != NULL);
  CommandBuff_descriptor_ = file->message_type(0);
  static const int CommandBuff_offsets_[1] = {
  };
  CommandBuff_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CommandBuff_descriptor_,
      CommandBuff::default_instance_,
      CommandBuff_offsets_,
      -1,
      -1,
      -1,
      sizeof(CommandBuff),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandBuff, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandBuff, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_proto_2fCommandBuff_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CommandBuff_descriptor_, &CommandBuff::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_proto_2fCommandBuff_2eproto() {
  delete CommandBuff::default_instance_;
  delete CommandBuff_reflection_;
}

void protobuf_AddDesc_proto_2fCommandBuff_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027proto/CommandBuff.proto\"\r\n\013CommandBuff"
    "b\006proto3", 48);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/CommandBuff.proto", &protobuf_RegisterTypes);
  CommandBuff::default_instance_ = new CommandBuff();
  CommandBuff::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_proto_2fCommandBuff_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_proto_2fCommandBuff_2eproto {
  StaticDescriptorInitializer_proto_2fCommandBuff_2eproto() {
    protobuf_AddDesc_proto_2fCommandBuff_2eproto();
  }
} static_descriptor_initializer_proto_2fCommandBuff_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CommandBuff::CommandBuff()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CommandBuff)
}

void CommandBuff::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CommandBuff::CommandBuff(const CommandBuff& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CommandBuff)
}

void CommandBuff::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

CommandBuff::~CommandBuff() {
  // @@protoc_insertion_point(destructor:CommandBuff)
  SharedDtor();
}

void CommandBuff::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CommandBuff::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommandBuff::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommandBuff_descriptor_;
}

const CommandBuff& CommandBuff::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_2fCommandBuff_2eproto();
  return *default_instance_;
}

CommandBuff* CommandBuff::default_instance_ = NULL;

CommandBuff* CommandBuff::New(::google::protobuf::Arena* arena) const {
  CommandBuff* n = new CommandBuff;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CommandBuff::Clear() {
}

bool CommandBuff::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CommandBuff)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:CommandBuff)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CommandBuff)
  return false;
#undef DO_
}

void CommandBuff::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CommandBuff)
  // @@protoc_insertion_point(serialize_end:CommandBuff)
}

::google::protobuf::uint8* CommandBuff::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CommandBuff)
  // @@protoc_insertion_point(serialize_to_array_end:CommandBuff)
  return target;
}

int CommandBuff::ByteSize() const {
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommandBuff::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CommandBuff* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CommandBuff>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommandBuff::MergeFrom(const CommandBuff& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
}

void CommandBuff::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommandBuff::CopyFrom(const CommandBuff& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandBuff::IsInitialized() const {

  return true;
}

void CommandBuff::Swap(CommandBuff* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CommandBuff::InternalSwap(CommandBuff* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CommandBuff::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommandBuff_descriptor_;
  metadata.reflection = CommandBuff_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CommandBuff

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
