# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/CommandBuff.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/CommandBuff.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x17proto/CommandBuff.proto\"\r\n\x0b\x43ommandBuffb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMMANDBUFF = _descriptor.Descriptor(
  name='CommandBuff',
  full_name='CommandBuff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=40,
)

DESCRIPTOR.message_types_by_name['CommandBuff'] = _COMMANDBUFF

CommandBuff = _reflection.GeneratedProtocolMessageType('CommandBuff', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDBUFF,
  __module__ = 'proto.CommandBuff_pb2'
  # @@protoc_insertion_point(class_scope:CommandBuff)
  ))
_sym_db.RegisterMessage(CommandBuff)


# @@protoc_insertion_point(module_scope)
