protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python AllConnections.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python KwmConnection.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python KwmConnections.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python LockProto.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python LockProtos.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python MatrixProto.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python MatrixProtos.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python MattiRequest.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python MattiResponse.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python ProgramProto.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python ProgramProtos.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python TimerProto.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python TimerProtos.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python VideoConnection.proto
protoc --csharp_out=csharp --cpp_out=cpp --objc_out=objc --java_out=java --python_out=python VideoConnections.proto